---
title: Coding Nights
date: 02-07-2024
---

With the aim to improve the coding culture of IITGN and help the students get equipped with the necessary industrial and coding skills, we are introducing coding nights! The event will create a positive competitive environment among the students, leading to healthy competition and great learning outcomes. 

## Structure:
### Coding Contest:
Coding contests often occur on websites like Codeforces and CodeChef. These contests would be used to engage the students. We will consider only individual participation.

### Problem Solving Session:
The contests will be followed by a problem-solving session by GRASP. This will help enhance the students’ skills.

The winners (Top 2/3) of each contest will get a special T-shirt.

Some of the Possible Contests:
CodeChef Starters, and Div3/Div4 of Codeforces.

CodeChef and Codeforces are one of the most popular platforms for competitive coding. They provide high-quality novel questions. As these platforms are very popular, the problem solutions are also readily available online.

The contests are necessary to upskill. However, these clash with the mess timings. Therefore, we will be serving food and refreshments to the students. This will make it feasible for the students to participate in these sessions. 

In this event's first edition, we aim to conduct four contests. 